# Generated by Django 3.2.3 on 2023-12-31 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Обязательное поле. Например, #8000ff - это фиолетовый цвет.', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате Hex', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет'),
        ),
    ]
