# Generated by Django 3.2 on 2023-12-14 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0.0001, message='Количество должно быть больше нуля')], verbose_name='Количество'),
        ),
    ]
