# Generated by Django 3.2 on 2023-12-14 08:44

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_unique_name_measurement_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': (django.db.models.functions.text.Lower('name'),), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
